version: '3.7'

x-process-variables: &process-variables
  PUID : 1000
  PGID : 1000

x-auth-variables: &auth-variables
  NGINX_BASIC_AUTH : 'true'
  NGINX_LDAP_TLS_STUNNEL : 'false'
  NGINX_LDAP_TLS_STUNNEL_CHECK_HOST : ''
  NGINX_LDAP_TLS_STUNNEL_CHECK_IP : ''
  NGINX_LDAP_TLS_STUNNEL_VERIFY_LEVEL : 2
  NGINX_SSL : 'true'

################################################################################

services:

  whoami:
    image: traefik/whoami:latest
    container_name: whoami
    restart: "no"
    hostname: whoami

  nginx-ldap:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/mmguero/nginx-ldap:latest
    container_name: nginx-ldap
    hostname: nginx-ldap
    restart: "no"
    environment:
      << : *process-variables
      << : *auth-variables
    depends_on:
      - whoami
    ports:
      - "127.0.0.1:32443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_ldap.conf:/etc/nginx/nginx_ldap.conf:ro
      - ./nginx/htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/ca-trust:/etc/nginx/ca-trust:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
    healthcheck:
      test: ["CMD", "curl", "--insecure", "--silent", "https://localhost:443"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
