---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-loadbalancer
  namespace: ingress-nginx
spec:
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ldap
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-ldap
            port:
              number: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ldap
spec:
  ports:
    - port: 8000
      protocol: TCP
  selector:
    app:  nginx-ldap
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app:  nginx-ldap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ldap-nginx
spec:
  selector:
    matchLabels:
      app: nginx-ldap
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-ldap
    spec:
      containers:
      - name: whoami
        image: traefik/whoami:latest
        ports:
          - containerPort: 80
      - name: nginx-ldap
        image: docker.io/mmguero/nginx-ldap:latest
        ports:
        - containerPort: 8000
        env:
          - name: PUID
            value: '1000'
          - name: PGID
            value: '1000'
          - name: NGINX_BASIC_AUTH
            value: 'true'
          - name: NGINX_LDAP_TLS_STUNNEL
            value: 'false'
          - name: NGINX_LDAP_TLS_STUNNEL_CHECK_HOST
            value: ''
          - name: NGINX_LDAP_TLS_STUNNEL_CHECK_IP
            value: ''
          - name: NGINX_LDAP_TLS_STUNNEL_VERIFY_LEVEL
            value: '2'
          - name: NGINX_SSL
            value: 'false'
          - name: CONFIG_MAP_DIR
            value: 'configmap'
        volumeMounts:
        - name: etc-nginx-volume
          mountPath: /etc/nginx/configmap
        - name: etc-nginx-catrust-volume
          mountPath: /etc/nginx/ca-trust/configmap
        - name: etc-nginx-certs-volume
          mountPath: /etc/nginx/certs/configmap
        - name: etc-nginx-certs-pem-volume
          mountPath: /etc/nginx/dhparam/configmap
      volumes:
      - name: etc-nginx-volume
        configMap:
          name: etc-nginx
      - name: etc-nginx-catrust-volume
        configMap:
          name: etc-nginx-catrust
      - name: etc-nginx-certs-volume
        configMap:
          name: etc-nginx-certs
      - name: etc-nginx-certs-pem-volume
        configMap:
          name: etc-nginx-certs-pem